"use client";
import {FormEvent,useMemo,useState} from "react";
import type {Client} from "../../lib/supabase";
import "./Financial.css";
type Category={id:string;name:string;kind:"receita"|"despesa"|"ambos";color:string};
type Transaction={id:string;kind:"receita"|"despesa";description:string;category_id:string|null;client_id:string|null;supplier:string|null;amount:number;due_date:string;paid_at:string|null;status:"pendente"|"pago"|"cancelado";payment_method:string|null;installment_number:number;installment_total:number;financial_categories?:{name:string;color:string};clients?:{name:string}};
async function act(body:Record<string,unknown>){const r=await fetch("/api/actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error);return j}
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export function Financial({transactions,categories,clients,reload}:{transactions:Transaction[];categories:Category[];clients:Client[];reload:()=>void}){
 const [open,setOpen]=useState(false),[kind,setKind]=useState<"receita"|"despesa">("receita"),[filter,setFilter]=useState("todos"),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[error,setError]=useState("");
 const rows=useMemo(()=>transactions.filter(x=>(filter==="todos"||x.status===filter)&&(!month||x.due_date.startsWith(month))),[transactions,filter,month]);
 const valid=transactions.filter(x=>x.status!=="cancelado"),received=valid.filter(x=>x.kind==="receita"&&x.status==="pago").reduce((a,x)=>a+Number(x.amount),0),paid=valid.filter(x=>x.kind==="despesa"&&x.status==="pago").reduce((a,x)=>a+Number(x.amount),0),receivable=valid.filter(x=>x.kind==="receita"&&x.status==="pendente").reduce((a,x)=>a+Number(x.amount),0),payable=valid.filter(x=>x.kind==="despesa"&&x.status==="pendente").reduce((a,x)=>a+Number(x.amount),0);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await act({action:"financial-create",kind,description:f.get("description"),category_id:f.get("category"),client_id:f.get("client"),supplier:f.get("supplier"),amount:Number(f.get("amount")),due_date:f.get("due_date"),installments:Number(f.get("installments")),notes:f.get("notes")});setOpen(false);reload()}catch(x){setError(x instanceof Error?x.message:"Erro ao salvar")}}
 async function pay(id:string){await act({action:"financial-pay",id,payment_method:"Manual"});reload()}
 async function cancel(id:string){if(confirm("Cancelar este lançamento?")){await act({action:"financial-cancel",id});reload()}}
 function csv(){const data=[["Tipo","Descrição","Categoria","Cliente/Fornecedor","Valor","Vencimento","Status"],...rows.map(x=>[x.kind,x.description,x.financial_categories?.name||"",x.clients?.name||x.supplier||"",String(x.amount),x.due_date,x.status])];const blob=new Blob(["\ufeff"+data.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n")],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`financeiro-melin-${month||"completo"}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <><div className="page-intro"><div><h2>Controle financeiro</h2><p>Contas a pagar e receber, fluxo de caixa, parcelas e baixas.</p></div><div className="actions"><button className="outline" onClick={csv}>↓ Exportar CSV</button><button className="primary" onClick={()=>setOpen(true)}>＋ Novo lançamento</button></div></div>
 <div className="metrics finance-metrics"><article className="metric"><div className="metric-top"><span>Saldo realizado</span></div><div><strong>{money(received-paid)}</strong></div><p>Recebido menos pago</p></article><article className="metric"><div className="metric-top"><span>Contas a receber</span></div><div><strong>{money(receivable)}</strong></div><p>Valores pendentes</p></article><article className="metric"><div className="metric-top"><span>Contas a pagar</span></div><div><strong>{money(payable)}</strong></div><p className="orange">Valores pendentes</p></article><article className="metric"><div className="metric-top"><span>Resultado previsto</span></div><div><strong>{money(received+receivable-paid-payable)}</strong></div><p>Incluindo pendências</p></article></div>
 <section className="card table-card"><div className="finance-toolbar"><div><span>LANÇAMENTOS</span><h3>Fluxo financeiro</h3></div><div><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="todos">Todos</option><option value="pendente">Pendentes</option><option value="pago">Pagos</option><option value="cancelado">Cancelados</option></select></div></div>{rows.length===0?<div className="empty">Nenhum lançamento neste período.</div>:rows.map(x=><div className="finance-row" key={x.id}><i className={x.kind}/><div><strong>{x.description}</strong><small>{x.financial_categories?.name||"Sem categoria"} · {x.clients?.name||x.supplier||"Geral"}{x.installment_total>1?` · ${x.installment_number}/${x.installment_total}`:""}</small></div><span>{new Date(x.due_date+"T12:00:00").toLocaleDateString("pt-BR")}</span><b className={x.kind}>{x.kind==="receita"?"+":"−"} {money(Number(x.amount))}</b><em className={x.status}>{x.status}</em><div>{x.status==="pendente"&&<button onClick={()=>pay(x.id)}>Dar baixa</button>}{x.status!=="cancelado"&&<button className="cancel" onClick={()=>cancel(x.id)}>×</button>}</div></div>)}</section>
 {open&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><button type="button" className="modal-close" onClick={()=>setOpen(false)}>×</button><span>FINANCEIRO</span><h2>Novo lançamento</h2><div className="finance-kind"><button type="button" className={kind==="receita"?"selected":""} onClick={()=>setKind("receita")}>Conta a receber</button><button type="button" className={kind==="despesa"?"selected":""} onClick={()=>setKind("despesa")}>Conta a pagar</button></div><label>Descrição<input name="description" required/></label><div className="form-grid"><label>Categoria<select name="category"><option value="">Sem categoria</option>{categories.filter(c=>c.kind===kind||c.kind==="ambos").map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Valor total<input name="amount" type="number" min="0.01" step="0.01" required/></label></div>{kind==="receita"?<label>Cliente<select name="client"><option value="">Nenhum</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>:<label>Fornecedor<input name="supplier"/></label>}<div className="form-grid"><label>Primeiro vencimento<input name="due_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Parcelas/recorrências<input name="installments" type="number" min="1" max="60" defaultValue="1"/></label></div><label>Observações<textarea name="notes"/></label>{error&&<div className="login-error">{error}</div>}<button className="primary submit">Salvar lançamento</button></form></div>}</>
}
