import { hash } from "bcryptjs";
import { getSession } from "../../../lib/server-auth";
import { serverSupabase } from "../../../lib/server-supabase";
export async function POST(request:Request){const session=await getSession(request);if(!session)return Response.json({error:"Sessão expirada"},{status:401});const b=await request.json(),s=serverSupabase(),admin=session.role==="admin";try{let e:any=null,entityId:string|undefined;
if(b.action==="product"){if(!["admin","estoque"].includes(session.role))throw new Error("Sem permissão");const r=await s.from("products").insert({name:b.name,sku:b.sku,current_stock:b.stock,min_stock:b.min}).select("id").single();e=r.error;entityId=r.data?.id}
else if(b.action==="update-product"){if(!["admin","estoque"].includes(session.role))throw new Error("Sem permissão");({error:e}=await s.from("products").update({name:b.name,sku:b.sku,min_stock:b.min,active:b.active}).eq("id",b.id));entityId=b.id}
else if(b.action==="movement"){if(!["admin","estoque","repositor"].includes(session.role))throw new Error("Sem permissão");const r=await s.from("stock_movements").insert({product_id:b.product,client_id:b.client||null,movement_type:b.movement_type,quantity:b.quantity,notes:b.notes||null}).select("id").single();e=r.error;entityId=r.data?.id}
else if(b.action==="client"){if(!["admin","comercial"].includes(session.role))throw new Error("Sem permissão");const r=await s.from("clients").insert({name:b.name,phone:b.phone||null,address:b.address,neighborhood:b.neighborhood||null,city:b.city,current_stock:b.stock,min_stock:b.min,latitude:b.latitude,longitude:b.longitude}).select("id").single();e=r.error;entityId=r.data?.id}
else if(b.action==="update-client"){if(!["admin","comercial"].includes(session.role))throw new Error("Sem permissão");({error:e}=await s.from("clients").update({name:b.name,phone:b.phone,address:b.address,neighborhood:b.neighborhood,min_stock:b.min,latitude:b.latitude,longitude:b.longitude,active:b.active}).eq("id",b.id));entityId=b.id}
else if(b.action==="client-stock"){if(!["admin","estoque","repositor"].includes(session.role))throw new Error("Sem permissão");({error:e}=await s.from("client_product_stock").upsert({client_id:b.client_id,product_id:b.product_id,current_stock:b.stock,min_stock:b.min,updated_at:new Date().toISOString()},{onConflict:"client_id,product_id"}));entityId=b.client_id}
else if(b.action==="user"){if(!admin)throw new Error("Somente administradores");const password_hash=await hash(b.password,10);const r=await s.from("app_users").insert({name:b.name,email:String(b.email).toLowerCase(),password_hash,role:b.role}).select("id").single();e=r.error;entityId=r.data?.id}
else if(b.action==="toggle-user"){if(!admin)throw new Error("Somente administradores");({error:e}=await s.from("app_users").update({active:b.active}).eq("id",b.id));entityId=b.id}
else if(b.action==="financial-create"){if(!admin)throw new Error("Somente administradores");const total=Math.max(1,Number(b.installments)||1),group=total>1?crypto.randomUUID():null,start=new Date(`${b.due_date}T12:00:00`),rows=Array.from({length:total},(_,i)=>{const due=new Date(start);due.setMonth(due.getMonth()+i);return {kind:b.kind,description:b.description,category_id:b.category_id||null,client_id:b.client_id||null,supplier:b.supplier||null,amount:Math.round(Number(b.amount)*100/total)/100,due_date:due.toISOString().slice(0,10),status:"pendente",notes:b.notes||null,installment_number:i+1,installment_total:total,recurrence_group:group}});const r=await s.from("financial_transactions").insert(rows).select("id");e=r.error;entityId=r.data?.[0]?.id}
else if(b.action==="financial-pay"){if(!admin)throw new Error("Somente administradores");({error:e}=await s.from("financial_transactions").update({status:"pago",paid_at:b.paid_at||new Date().toISOString().slice(0,10),payment_method:b.payment_method||null}).eq("id",b.id));entityId=b.id}
else if(b.action==="financial-cancel"){if(!admin)throw new Error("Somente administradores");({error:e}=await s.from("financial_transactions").update({status:"cancelado"}).eq("id",b.id));entityId=b.id}
else if(b.action==="financial-category"){if(!admin)throw new Error("Somente administradores");const r=await s.from("financial_categories").insert({name:b.name,kind:b.kind,color:b.color||"#0c5039"}).select("id").single();e=r.error;entityId=r.data?.id}
else if(b.action==="route"){if(!["admin","repositor"].includes(session.role))throw new Error("Sem permissão");await s.from("routes").update({status:"cancelada"}).not("status","in",'("concluida","cancelada")');if(b.stops.length){const r=await s.from("routes").insert({status:"planejada",route_date:new Date().toISOString().slice(0,10)}).select("id").single();e=r.error;entityId=r.data?.id;if(r.data&&!e)({error:e}=await s.from("route_stops").insert(b.stops.map((x:any)=>({...x,route_id:r.data.id}))))}}
else if(b.action==="complete"){if(!["admin","repositor"].includes(session.role))throw new Error("Sem permissão");let productId=b.product_id;if(!productId){const p=await s.from("products").select("id").eq("active",true).order("created_at").limit(1).single();productId=p.data?.id}if(!productId)throw new Error("Cadastre um produto antes de confirmar");const u=await s.from("route_stops").update({status:"concluida",delivered_quantity:b.quantity,completed_at:new Date().toISOString()}).eq("id",b.stop_id);e=u.error;if(!e)({error:e}=await s.from("stock_movements").insert({product_id:productId,client_id:b.client_id,movement_type:"reposicao",quantity:b.quantity,notes:"Entrega confirmada pela rota"}));entityId=b.stop_id}
else return Response.json({error:"Ação inválida"},{status:400});if(e)throw new Error(e.message);await s.from("audit_logs").insert({user_email:session.email,action:b.action,entity_type:b.action.split("-").at(-1)||b.action,entity_id:entityId,details:{source:"webapp"}});return Response.json({ok:true})}catch(e){return Response.json({error:e instanceof Error?e.message:"Erro ao salvar"},{status:400})}}
