"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import nextDynamic from "next/dynamic";
import type { Client, Product, Movement } from "../lib/supabase";
import Login from "./login";
import { ClientInventoryEditor, ProductEditor, Reports, Users } from "./components/AdminExtras";
import { Financial } from "./components/Financial";
const MapView=nextDynamic(()=>import("./components/MapView"),{ssr:false});
export const dynamic = "force-dynamic";

type Modal = "movement"|"product"|"client"|null;
type Stop={id:string;client_id:string;stop_order:number;planned_quantity:number;delivered_quantity:number|null;status:string;clients?:Client};
const nav=["Visão geral","Estoque","Clientes","Rotas","Financeiro","Pontos de venda","Relatórios","Usuários"];
async function apiAction(body:Record<string,unknown>){const r=await fetch("/api/actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Erro ao salvar");return j}
async function fetchWithTimeout(url:string,options:RequestInit={},timeout=12000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(url,{...options,signal:controller.signal,cache:"no-store"})}finally{clearTimeout(timer)}}

export default function Home(){
 const [authenticated,setAuthenticated]=useState<boolean|null>(null);
 const [mobileMenu,setMobileMenu]=useState(false);
 const [clientStocks,setClientStocks]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[session,setSession]=useState<any>(null),[financialCategories,setFinancialCategories]=useState<any[]>([]),[financialTransactions,setFinancialTransactions]=useState<any[]>([]);
 const [active,setActive]=useState("Visão geral"),[products,setProducts]=useState<Product[]>([]),[clients,setClients]=useState<Client[]>([]),[movements,setMovements]=useState<Movement[]>([]),[stops,setStops]=useState<Stop[]>([]),[modal,setModal]=useState<Modal>(null),[editingClient,setEditingClient]=useState<Client|null>(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[query,setQuery]=useState("");
 async function load(){setLoading(true);try{const r=await fetchWithTimeout("/api/data");if(r.status===401){setAuthenticated(false);return}if(!r.ok)throw new Error("Não foi possível carregar os dados");const data=await r.json();setProducts(data.products||[]);setClients(data.clients||[]);setMovements(data.movements||[]);setStops(data.stops||[]);setClientStocks(data.clientStocks||[]);setUsers(data.users||[]);setAudit(data.audit||[]);setFinancialCategories(data.financialCategories||[]);setFinancialTransactions(data.financialTransactions||[]);setSession(data.session||null)}catch{setNotice("Não foi possível carregar os dados. Tente novamente.")}finally{setLoading(false)}}
 useEffect(()=>{let mounted=true;fetchWithTimeout("/api/auth/session").then(r=>r.ok?r.json():{authenticated:false}).then(x=>{if(!mounted)return;setAuthenticated(Boolean(x.authenticated));if(x.authenticated)load()}).catch(()=>{if(mounted)setAuthenticated(false)});return()=>{mounted=false}},[]);useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),3500);return()=>clearTimeout(t)},[notice]);
 function done(msg:string){setModal(null);setNotice(msg);load()}
 const normalizedQuery=query.trim().toLocaleLowerCase("pt-BR");
 const filtered=clients.filter(c=>`${c.name} ${c.neighborhood||""} ${c.address||""}`.toLocaleLowerCase("pt-BR").includes(normalizedQuery));
 async function logout(){await fetch("/api/auth/session",{method:"DELETE"});setAuthenticated(false)}
 if(authenticated===null)return <div className="session-loading"><img src="/logo.jpeg" alt="Paieiro Melin" width="72" height="72"/><strong>Validando acesso</strong><span>Aguarde um instante…</span></div>;
 if(!authenticated)return <Login success={()=>{setAuthenticated(true);load()}}/>;
 return <main className={`app-shell ${mobileMenu?"menu-open":""}`}><button className="menu-backdrop" aria-label="Fechar menu" onClick={()=>setMobileMenu(false)}/><aside className="sidebar"><div className="brand"><img src="/logo.jpeg" alt="Paieiro Melin"/><div><strong>MELIN</strong><span>APP</span></div><button className="menu-close" onClick={()=>setMobileMenu(false)} aria-label="Fechar menu">×</button></div><nav>{nav.map((x,i)=><button key={x} className={active===x?"active":""} onClick={()=>{setActive(x);setMobileMenu(false)}}><span className="nav-icon">{["⌂","▦","◉","↗","$","⌖","▤","♙"][i]}</span>{x}</button>)}</nav><div className="sidebar-note"><span>ROTA ATUAL</span><strong>{stops.length} paradas</strong><small>{stops.filter(s=>s.status==="concluida").length} concluídas</small><button onClick={()=>{setActive("Rotas");setMobileMenu(false)}}>Ver rota completa →</button></div><div className="profile"><span>RM</span><div><strong>Gestão Melin</strong><small>Administrador</small></div></div></aside>
 <section className="workspace"><header><button className="mobile-menu-button" onClick={()=>setMobileMenu(true)} aria-label="Abrir menu">☰</button><div><p>OPERAÇÃO MELIN</p><h1>{active}</h1></div><div className="header-actions"><button className="logout-btn" onClick={logout}>Sair</button><button className="icon-btn">♢<i>{clients.filter(c=>c.current_stock<c.min_stock).length}</i></button><button className="primary" onClick={()=>setModal("movement")}>＋ Nova movimentação</button></div></header>
 {loading?<div className="loading">Carregando dados da operação…</div>:<div className="content">
 {active==="Visão geral"&&<Dashboard products={products} clients={clients} movements={movements} stops={stops} go={setActive}/>} 
 {active==="Estoque"&&<><Stock products={products} movements={movements} add={()=>setModal("product")} move={()=>setModal("movement")}/><ProductEditor products={products} reload={load}/></>} 
 {active==="Clientes"&&<><Clients clients={filtered} total={clients.length} query={query} setQuery={setQuery} add={()=>setModal("client")} edit={setEditingClient}/><ClientInventoryEditor products={products} clients={clients} reload={load}/></>}
 {active==="Rotas"&&<Routes clients={clients} stops={stops} done={done}/>} 
 {active==="Financeiro"&&session?.role==="admin"&&<Financial transactions={financialTransactions} categories={financialCategories} clients={clients} reload={load}/>}
 {active==="Pontos de venda"&&<Points clients={clients}/>} 
 {active==="Relatórios"&&<Reports products={products} clients={clients} movements={movements} clientStocks={clientStocks}/>} 
 {active==="Usuários"&&session?.role==="admin"&&<Users users={users} audit={audit} reload={load}/>} </div>}
 </section>{modal&&<ModalBox type={modal} products={products} clients={clients} close={()=>setModal(null)} done={done}/>} {editingClient&&<EditClientModal client={editingClient} close={()=>setEditingClient(null)} done={msg=>{setEditingClient(null);done(msg)}}/>} {notice&&<div className="toast">✓ {notice}</div>}</main>
}

function Dashboard({products,clients,movements,stops,go}:{products:Product[];clients:Client[];movements:Movement[];stops:Stop[];go:(x:string)=>void}){const total=products.reduce((a,p)=>a+p.current_stock,0),priority=clients.filter(c=>c.current_stock<c.min_stock);return <><div className="welcome"><div><span>OPERAÇÃO EM TEMPO REAL</span><h2>Bom dia.</h2><p>Há <strong>{priority.length} pontos</strong> que precisam de reposição.</p></div><button onClick={()=>go("Rotas")}>Planejar rota <span>→</span></button></div><div className="metrics"><Metric label="Estoque total" value={String(total)} unit="unidades"/><Metric label="Pontos ativos" value={String(clients.length)} unit="clientes"/><Metric label="Movimentações" value={String(movements.length)} unit="recentes"/><Metric label="Rota atual" value={String(stops.length)} unit="paradas"/></div><div className="dashboard-grid"><section className="card attention"><Title top="ATENÇÃO NECESSÁRIA" title="Reposições prioritárias"/><ClientRows clients={priority.slice(0,4)}/></section><section className="card route-card"><Title top="ROTA OTIMIZADA" title="Roteiro atual"/><div className="route-summary"><div><strong>{stops.length}</strong><small>paradas</small></div><div><strong>{stops.filter(s=>s.status==="concluida").length}</strong><small>concluídas</small></div><div><strong>{stops.reduce((a,s)=>a+s.planned_quantity,0)}</strong><small>unidades</small></div></div><button className="route-button" onClick={()=>go("Rotas")}>Abrir roteiro do dia →</button></section></div></>}
function Metric({label,value,unit}:{label:string;value:string;unit:string}){return <article className="metric"><div className="metric-top"><span>{label}</span><i>▦</i></div><div><strong>{value}</strong><small>{unit}</small></div><p>● Atualizado agora</p></article>}
function Title({top,title,action}:{top:string;title:string;action?:React.ReactNode}){return <div className="section-title"><div><span>{top}</span><h3>{title}</h3></div>{action}</div>}
function ClientRows({clients}:{clients:Client[]}){return <>{clients.length===0?<div className="empty">Nenhum ponto requer atenção.</div>:clients.map(c=><div className="client-row" key={c.id}><div className="avatar">{c.name.slice(0,2).toUpperCase()}</div><div className="client-name"><strong>{c.name}</strong><small>{c.neighborhood} · {c.city}</small></div><div className="stock"><small>ESTOQUE</small><strong>{c.current_stock} un.</strong></div><span className={`status ${c.current_stock<c.min_stock?"urgent":"ok"}`}>{c.current_stock<c.min_stock?"Repor":"Estável"}</span></div>)}</>}
function Stock({products,movements,add,move}:{products:Product[];movements:Movement[];add:()=>void;move:()=>void}){return <><div className="page-intro"><div><h2>Controle de estoque</h2><p>Produtos e movimentações atualizados pelo banco.</p></div><div className="actions"><button className="outline" onClick={add}>＋ Novo produto</button><button className="primary" onClick={move}>Registrar movimento</button></div></div><section className="card table-card"><Title top="INVENTÁRIO" title="Posição por produto"/>{products.map(p=><div className="inventory" key={p.id}><div className="product-dot"/><div><strong>{p.name}</strong><small>{p.sku}</small></div><b>{p.current_stock} un.</b><div className="progress"><i style={{width:`${Math.min(100,p.current_stock/Math.max(1,p.min_stock)*50)}%`}}/></div><span className={`status ${p.current_stock<p.min_stock?"urgent":"ok"}`}>{p.current_stock<p.min_stock?"Baixo":"Saudável"}</span></div>)}</section><section className="card table-card recent"><Title top="HISTÓRICO" title="Movimentações recentes"/>{movements.map(m=><div className="history" key={m.id}><span className={`movement-type ${m.movement_type}`}>{m.movement_type}</span><strong>{products.find(p=>p.id===m.product_id)?.name||"Produto"}</strong><b>{m.movement_type==="entrada"?"+":"−"}{m.quantity} un.</b><small>{new Date(m.created_at).toLocaleString("pt-BR")}</small></div>)}</section></>}
function Clients({clients,total,query,setQuery,add,edit}:{clients:Client[];total:number;query:string;setQuery:(x:string)=>void;add:()=>void;edit:(client:Client)=>void}){return <><div className="page-intro"><div><h2>Clientes e pontos atendidos</h2><p>Cadastre endereços e acompanhe a necessidade de reposição.</p></div><button className="primary" onClick={add}>＋ Novo cliente</button></div><div className="client-search"><span>⌕</span><input className="search wide" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome, bairro ou endereço…" autoComplete="off"/>{query&&<button onClick={()=>setQuery("")} aria-label="Limpar busca">×</button>}<small>{clients.length} de {total}</small></div><section className="card table-card">{clients.length===0?<div className="empty">Nenhum cliente encontrado para “{query}”.</div>:clients.map(c=><div className="client-row large" key={c.id}><div className="avatar">{c.name.slice(0,2).toUpperCase()}</div><div className="client-name"><div className="client-name-line"><strong>{c.name}</strong><button className="inline-edit" onClick={()=>edit(c)}>Editar</button></div><small>{c.address} · {c.neighborhood}</small></div><div className="stock"><small>ESTOQUE / MÍNIMO</small><strong>{c.current_stock} / {c.min_stock} un.</strong></div><span className={`status ${c.current_stock<c.min_stock?"urgent":"ok"}`}>{c.current_stock<c.min_stock?"Repor":"Estável"}</span>{c.latitude&&c.longitude?<a className="outline" target="_blank" href={`https://www.openstreetmap.org/?mlat=${c.latitude}&mlon=${c.longitude}#map=16/${c.latitude}/${c.longitude}`}>Ver mapa</a>:<span className="map-missing">Sem localização</span>}</div>)}</section></>}
function Routes({clients,stops,done}:{clients:Client[];stops:Stop[];done:(x:string)=>void}){const completedIds=new Set(stops.filter(s=>s.status==="concluida").map(s=>s.client_id));const priority=clients.filter(c=>c.current_stock<c.min_stock&&c.latitude&&c.longitude&&!completedIds.has(c.id));async function optimize(){let remaining=[...priority],current={latitude:-21.7878,longitude:-46.5614},ordered:Client[]=[];while(remaining.length){remaining.sort((a,b)=>dist(current,a)-dist(current,b));const next=remaining.shift()!;ordered.push(next);current=next}try{await apiAction({action:"route",stops:ordered.map((c,i)=>({client_id:c.id,stop_order:i+1,planned_quantity:Math.max(0,c.min_stock*2-c.current_stock)}))});done(ordered.length?"Rota otimizada apenas com entregas pendentes":"Todas as entregas foram concluídas; rota encerrada")}catch(e){done(e instanceof Error?e.message:"Erro ao criar rota")}}async function complete(s:Stop){try{await apiAction({action:"complete",stop_id:s.id,client_id:s.client_id,quantity:s.planned_quantity});done("Entrega confirmada e estoques atualizados")}catch(e){done(e instanceof Error?e.message:"Erro ao confirmar")}}const pendingStops=stops.filter(s=>s.status!=="concluida");const points=pendingStops.filter(s=>s.clients?.latitude&&s.clients?.longitude).map(s=>({id:s.id,name:s.clients!.name,latitude:s.clients!.latitude!,longitude:s.clients!.longitude!,order:s.stop_order}));const destination=points.at(-1),waypoints=points.slice(0,-1).map(p=>`${p.latitude},${p.longitude}`).join("|");const googleUrl=destination?`https://www.google.com/maps/dir/?api=1&origin=-21.7878,-46.5614&destination=${destination.latitude},${destination.longitude}&travelmode=driving${waypoints?`&waypoints=${encodeURIComponent(waypoints)}`:""}`:"";return <><div className="page-intro"><div><h2>Rota de reposição</h2><p>Ordem calculada pela proximidade dos clientes prioritários.</p></div><div className="route-actions"><button className="primary" onClick={optimize}>↗ Otimizar rota agora</button>{googleUrl&&<a className="google-route" href={googleUrl} target="_blank" rel="noreferrer">Abrir no Google Maps ↗</a>}</div></div><div className="routes-layout"><section className="card stops"><Title top="ROTEIRO PENDENTE" title={`${pendingStops.length} paradas`}/>{pendingStops.length===0?<div className="empty">Nenhuma entrega pendente. Clique em “Otimizar rota” para encerrar o roteiro.</div>:pendingStops.map(s=><div className="stop" key={s.id}><span>{s.stop_order}</span><div><strong>{s.clients?.name}</strong><p>{s.clients?.address}</p></div><b>{s.planned_quantity} un.</b><button onClick={()=>complete(s)}>Confirmar</button></div>)}</section><section className="big-map"><MapView points={points} route/></section></div></>}
function dist(a:{latitude:number|null;longitude:number|null},b:{latitude:number|null;longitude:number|null}){return Math.hypot((a.latitude||0)-(b.latitude||0),(a.longitude||0)-(b.longitude||0))}
function Points({clients}:{clients:Client[]}){const [user,setUser]=useState<[number,number]|null>(null),[error,setError]=useState("");const mapped=clients.filter(c=>c.latitude&&c.longitude).map(c=>({...c,latitude:c.latitude!,longitude:c.longitude!}));const nearby=useMemo(()=>[...mapped].sort((a,b)=>user?dist({latitude:user[0],longitude:user[1]},a)-dist({latitude:user[0],longitude:user[1]},b):0),[user,clients]);function locate(){navigator.geolocation.getCurrentPosition(p=>{setUser([p.coords.latitude,p.coords.longitude]);setError("")},()=>setError("Não foi possível acessar sua localização. Autorize o navegador e tente novamente."),{enableHighAccuracy:true})}return <><div className="locator"><div><span>ENCONTRE PAIEIRO MELIN</span><h2>Onde comprar perto de você</h2><p>Veja os pontos de venda em Poços de Caldas.</p><button className="primary" onClick={locate}>⌖ {user?"Localização encontrada":"Usar minha localização"}</button>{error&&<small className="geo-error">{error}</small>}</div></div><div className="points-grid"><section className="card point-list"><Title top="MAIS PRÓXIMOS" title={`${nearby.length} pontos encontrados`}/>{nearby.map((c,i)=><div className="point" key={c.id}><i>{i+1}</i><div><strong>{c.name}</strong><small>{c.address} · {c.neighborhood}</small><p>{c.current_stock>0?"Produto disponível":"Consulte disponibilidade"}</p></div><a target="_blank" href={`https://www.google.com/maps/dir/?api=1&destination=${c.latitude},${c.longitude}`}>Como chegar ↗</a></div>)}</section><section className="big-map public"><MapView points={nearby.map((c,i)=>({id:c.id,name:c.name,latitude:c.latitude,longitude:c.longitude,order:i+1}))} user={user}/></section></div></>}

function EditClientModal({client,close,done}:{client:Client;close:()=>void;done:(message:string)=>void}){const [saving,setSaving]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);let latitude=client.latitude,longitude=client.longitude;const fullAddress=`${f.get("address")}, ${f.get("city")}, MG, Brasil`;try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(fullAddress)}`);const data=await response.json();if(data[0]){latitude=Number(data[0].lat);longitude=Number(data[0].lon)}}catch{}try{await apiAction({action:"update-client",id:client.id,name:f.get("name"),phone:f.get("phone"),address:f.get("address"),neighborhood:f.get("neighborhood"),min:Number(f.get("min")),latitude,longitude,active:f.get("active")==="on"});done("Cliente atualizado com sucesso")}catch(e){setSaving(false);setError(e instanceof Error?e.message:"Erro ao atualizar cliente")}}return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="modal" onSubmit={submit}><button type="button" className="modal-close" onClick={close}>×</button><span>REDE DE CLIENTES</span><h2>Editar cliente</h2><label>Nome do ponto<input name="name" defaultValue={client.name} required/></label><label>Endereço<input name="address" defaultValue={client.address} placeholder="Rua e número" required/></label><div className="form-grid"><label>Bairro<input name="neighborhood" defaultValue={client.neighborhood||""}/></label><label>Cidade<input name="city" defaultValue={client.city||"Poços de Caldas"} required/></label></div><div className="form-grid"><label>Telefone<input name="phone" defaultValue={client.phone||""}/></label><label>Estoque mínimo<input name="min" type="number" min="0" defaultValue={client.min_stock} required/></label></div><label className="active-check"><input name="active" type="checkbox" defaultChecked={client.active}/> Cliente ativo</label>{error&&<div className="login-error">{error}</div>}<button className="primary submit" disabled={saving}>{saving?"Salvando…":"Salvar alterações"}</button></form></div>}

function ModalBox({type,products,clients,close,done}:{type:Modal;products:Product[];clients:Client[];close:()=>void;done:(x:string)=>void}){const [saving,setSaving]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);try{if(type==="product"){await apiAction({action:"product",name:f.get("name"),sku:f.get("sku"),stock:Number(f.get("stock")),min:Number(f.get("min"))});return done("Produto cadastrado")}if(type==="movement"){await apiAction({action:"movement",product:f.get("product"),client:f.get("client")||null,movement_type:f.get("movement_type"),quantity:Number(f.get("quantity")),notes:f.get("notes")});return done("Movimentação registrada")}const address=`${f.get("address")}, ${f.get("city")}, MG, Brasil`;let lat=null,lon=null;try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(address)}`);const j=await r.json();if(j[0]){lat=Number(j[0].lat);lon=Number(j[0].lon)}}catch{}await apiAction({action:"client",name:f.get("name"),phone:f.get("phone"),address:f.get("address"),neighborhood:f.get("neighborhood"),city:f.get("city"),stock:Number(f.get("stock")),min:Number(f.get("min")),latitude:lat,longitude:lon});done(lat?"Cliente cadastrado e localizado no mapa":"Cliente cadastrado; endereço não localizado")}catch(e){setSaving(false);done(e instanceof Error?e.message:"Erro ao salvar")}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="modal" onSubmit={submit}><button type="button" className="modal-close" onClick={close}>×</button><span>{type==="movement"?"ESTOQUE":type==="product"?"CATÁLOGO":"REDE DE CLIENTES"}</span><h2>{type==="movement"?"Nova movimentação":type==="product"?"Novo produto":"Novo cliente"}</h2>{type==="movement"&&<><label>Produto<select name="product" required>{products.map(p=><option value={p.id} key={p.id}>{p.name} ({p.current_stock} un.)</option>)}</select></label><div className="form-grid"><label>Tipo<select name="movement_type"><option value="entrada">Entrada</option><option value="saida">Saída</option><option value="perda">Perda</option><option value="reposicao">Reposição</option></select></label><label>Quantidade<input name="quantity" type="number" min="1" required/></label></div><label>Cliente (para reposição)<select name="client"><option value="">Nenhum</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Observação<textarea name="notes"/></label></>}{type==="product"&&<><label>Nome<input name="name" required/></label><div className="form-grid"><label>SKU<input name="sku" required/></label><label>Estoque inicial<input name="stock" type="number" min="0" defaultValue="0"/></label></div><label>Estoque mínimo<input name="min" type="number" min="0" defaultValue="50"/></label></>}{type==="client"&&<><label>Nome do ponto<input name="name" required/></label><label>Endereço<input name="address" placeholder="Rua e número" required/></label><div className="form-grid"><label>Bairro<input name="neighborhood"/></label><label>Cidade<input name="city" defaultValue="Poços de Caldas" required/></label></div><div className="form-grid"><label>Telefone<input name="phone"/></label><label>Estoque atual<input name="stock" type="number" min="0" defaultValue="0"/></label></div><label>Estoque mínimo<input name="min" type="number" min="0" defaultValue="20"/></label></>}<button className="primary submit" disabled={saving}>{saving?"Salvando…":"Salvar"}</button></form></div>}
