"use client";
import { useEffect, useRef, useState } from "react";
import QRCode from "qrcode";
import { toPng } from "html-to-image";

type Format="square"|"story";
export default function Divulgar(){
 const [format,setFormat]=useState<Format>("square"),[qr,setQr]=useState(""),[headline,setHeadline]=useState("Encontre Paieiro Melin perto de você"),[subtitle,setSubtitle]=useState("Aponte a câmera para o QR Code e descubra onde comprar em Poços de Caldas."),[downloading,setDownloading]=useState(false);const card=useRef<HTMLDivElement>(null);
 useEffect(()=>{QRCode.toDataURL(`${window.location.origin}/onde-comprar`,{width:700,margin:2,color:{dark:"#073d2d",light:"#fffdfa"},errorCorrectionLevel:"H"}).then(setQr)},[]);
 async function download(){if(!card.current)return;setDownloading(true);try{const data=await toPng(card.current,{cacheBust:true,pixelRatio:format==="square"?2:3.2,style:{transform:"none",margin:"0"}});const a=document.createElement("a");a.download=`paieiro-melin-${format==="square"?"feed":"stories"}.png`;a.href=data;a.click()}finally{setDownloading(false)}}
 return <main className="promo-page"><header><div className="promo-brand"><img src="/logo.jpeg" alt="Paieiro Melin"/><div><strong>MELIN</strong><span>CRIADOR DE DIVULGAÇÃO</span></div></div><a href="/onde-comprar">Ver página pública →</a></header><section className="promo-workspace"><aside className="promo-controls"><span>MATERIAL DE DIVULGAÇÃO</span><h1>Crie sua arte com QR Code</h1><p>Personalize o texto, escolha o formato e baixe a imagem pronta para publicar ou imprimir.</p><label>Formato<div className="format-buttons"><button className={format==="square"?"selected":""} onClick={()=>setFormat("square")}>▣ Feed<br/><small>1080 × 1080</small></button><button className={format==="story"?"selected":""} onClick={()=>setFormat("story")}>▯ Stories<br/><small>1080 × 1920</small></button></div></label><label>Chamada principal<textarea value={headline} maxLength={65} onChange={e=>setHeadline(e.target.value)}/></label><label>Texto de apoio<textarea value={subtitle} maxLength={150} onChange={e=>setSubtitle(e.target.value)}/></label><button className="primary promo-download" onClick={download} disabled={downloading||!qr}>{downloading?"Gerando imagem…":"↓ Baixar imagem em PNG"}</button><small className="promo-hint">O QR Code aponta automaticamente para a página “Onde comprar”.</small></aside><section className={`promo-stage ${format}`}><div className={`promo-card ${format}`} ref={card}><div className="promo-glow one"/><div className="promo-glow two"/><div className="promo-card-top"><img src="/logo.jpeg" alt=""/><div><strong>PAIEIRO</strong><b>MELIN</b></div></div><div className="promo-copy"><span>ENCONTRE. ESCOLHA. APRECIE.</span><h2>{headline}</h2><p>{subtitle}</p></div><div className="promo-qr-area">{qr&&<img src={qr} alt="QR Code para encontrar pontos de venda"/>}<div><strong>APONTE A CÂMERA</strong><p>e encontre o ponto de venda mais próximo</p><small>paieiromelin.com.br</small></div></div><footer><span>PRODUTO PARA MAIORES DE 18 ANOS</span><b>Poços de Caldas • MG</b></footer></div></section></section></main>
}
