-- Catálogo oficial. Preserva históricos ao desativar registros antigos.
insert into public.products(name,sku,category,unit,min_stock,current_stock,active)
values ('Paieiro 7 Unidades','P7-001','Paieiro','pacote',50,0,true)
on conflict(sku) do update set name=excluded.name,category=excluded.category,unit=excluded.unit,active=true;
update public.products set active=false where sku <> 'P7-001';

create temporary table melin_client_names(name text primary key) on commit drop;
insert into melin_client_names(name) values
('Bar do Tadeu'),('Conveniencia Champagnat'),('Emporio Paraiso'),('Garage Beer'),('Hort Fruti Aeroporto'),('Mercado Modelo'),('Padaria com voce 2'),('Altas horas conveniencia'),('Bastião 2'),('Chacara Reis'),('Conveniencia John Pinheiro'),('Conveniencia Ziggas'),('DA Arquitetura'),('Da Medicina Veterinaria'),('Gabriel Revendedor'),('Marechal Beer'),('Mercado Todo dia'),('Mercearia do Jeffinho'),('Mercearia Portuga'),('Mercearia Siqueira'),('Mercearia Vale das Antas'),('Padaria com voce'),('Padaria da Andreia'),('padaria do Pedão'),('Padaria Madali'),('Padaria mais voce'),('Padaria Pão de Queijo'),('Padaria Pão Gostoso'),('Padaria Togni'),('Padaria Tradição Mineira'),('Padaria Vila Rica'),('Padaria Villa dos paes'),('Supermercado Bom preço'),('Supermercado Castelani'),('Supermercado do Paulo'),('Supermercado Garcia'),('Supermercado mais economico'),('Supermercado Major'),('Supermercado Mendonça'),('Supermercado Quississana'),('Supermercado Reis'),('Supermercado Vieira'),('Tabacaria Ouro Verde'),('Tabacaria Smoking'),('Tabacolandia'),('Bar do Pedrão'),('Delicias Caipira'),('Geladeiras'),('Mercearia M e F'),('Padaria e Confeitaria IF Dutra'),('Padaria Filadelphia'),('Padaria mais voce 2'),('Padaria Tiradentes'),('Supermercado Gonçalves'),('Bar encontro dos Amigos'),('Barbearia Elegance'),('Bar do Baiano'),('Conveniencia Fora de Hora'),('Padaria quero mais'),('Peg Pag Pabus'),('Resenha Conveniencia'),('Thiago Loucura'),('Agropesca'),('Caiu do Ceu'),('Gaucho''s Beer'),('Gleisson Advogado'),('Padaria Copacabana'),('Supermercado Limão'),('Padaria Amarilis'),('Rota Mercearia'),('Lanchonete da Lu'),('Tabacaria Terminal'),('Conveniencia Summer'),('Casa de carne Martins'),('Padaria 007'),('Padaria Pão Nosso'),('Bar do Evinho'),('Tribo da Roça'),('Padaria Center Pan'),('Bar do Denis'),('Padaria Raio de Luz'),('Restaurante Mineirinho'),('Casa de rações Uai'),('Ponto certo Conveniencia'),('Alfa Flix'),('Tabacaria'),('Charutaria'),('Bar esquina Esportiva'),('Rei do 1 Real'),('Deposito São Cristovão'),('Imperio Beer'),('Mercearia Mamá'),('Bar torresminho'),('Mega 1 real'),('Bar Guela Seca'),('Homer conveniencia Resedas'),('Conveniencia Stoppoint'),('Conveniencia Xingu'),('Bar do Mauricio'),('Bar Senador godoy'),('Distribuidora Rufino'),('Supermercado N e N'),('Bar do Ceará'),('Kaiser mercearia'),('Legal açougue e mercadinho'),('Mini mercado São Pedro'),('Supermercado Dom Marco'),('Bar e mercearia Teixeira'),('Bar do amarildo'),('Supermercado Jardim São Paulo'),('Conveniencia Pacaembu'),('Point Avenida'),('Mercearia Silvas'),('Conveniencia Ponto Zero'),('Bar Limonita'),('Bar do Cigano'),('Padaria Du Pão'),('Mercadinho da Ro'),('Supermercado RJ');

insert into public.clients(name,address,city,state,min_stock,current_stock,active)
select n.name,'Endereço a cadastrar','Poços de Caldas','MG',20,0,true
from melin_client_names n
where not exists (select 1 from public.clients c where lower(trim(c.name))=lower(trim(n.name)));
update public.clients c set active=true where exists (select 1 from melin_client_names n where lower(trim(n.name))=lower(trim(c.name)));
update public.clients c set active=false where not exists (select 1 from melin_client_names n where lower(trim(n.name))=lower(trim(c.name)));
